FROM liquibase/liquibase-slim:latest

USER root

RUN apk add --no-cache wget unzip gnupg

RUN wget "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -O "awscliv2.zip" && \
unzip awscliv2.zip && rm -rf awscliv2.zip && \
./aws/install

USER liquibase