name: Publish Liquibase Community README to Docker Hub

on:
  push:
    paths:
      - "README.md"
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  update-readme:
    uses: liquibase/build-logic/.github/workflows/reusable-docker-readme.yml@dat-22876-reusables
    with:
      target_image: liquibase/liquibase
      readme_path: README.md
      short_description: "Liquibase Community"
    secrets: inherit
