name: Publish Liquibase Secure README to Docker Hub

on:
  push:
    paths:
      - 'README-secure.md'
      - 'README-pro.md'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  
jobs:
  update-liquibase-secure-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials for vault access
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true

      - name: Decode DOCKERHUB_USERNAME
        run: |
          decoded_username=$(echo "${{ env.DOCKERHUB_USERNAME }}" | base64 -d)
          echo "DOCKERHUB_USERNAME_DECODED=$decoded_username" >> $GITHUB_ENV

      - name: Update Liquibase Secure README on Docker Hub
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_UPDATE_README }}
          repository: liquibase/liquibase-pro
          readme-filepath: ./README-secure.md
          short-description: "Liquibase Secure"
