name: Publish Liquibase Community README to Docker Hub

on:
  push:
    paths:
      - "README.md"
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  update-liquibase-Community-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials for vault access
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.LIQUIBASE_VAULT_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Get secrets from vault
        id: vault-secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@3a411b6ec5cace3d626412dd917e7bfeac242cfa # v3.0.0
        with:
          secret-ids: |
            ,/vault/liquibase
          parse-json-secrets: true

      - name: Decode DOCKERHUB_USERNAME
        run: |
          decoded_username=$(echo "${{ env.DOCKERHUB_USERNAME }}" | base64 -d)
          echo "DOCKERHUB_USERNAME_DECODED=$decoded_username" >> $GITHUB_ENV

      - name: Update Liquibase Community README on Docker Hub
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME_DECODED }}
          password: ${{ env.DOCKERHUB_UPDATE_README }}
          repository: liquibase/liquibase
          readme-filepath: README.md
          short-description: "Liquibase Community"
