# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Dockerfiles

on:
  push:
    branches: ["main"]
    paths:
      - 'Dockerfile*'
      - 'docker-entrypoint.sh'
      - '.github/workflows/test.yml'
      - '.github/test/**'
      - 'examples/**'
      - 'pom.xml'
  pull_request:
    branches: ["main"]
    paths:
      - 'Dockerfile*'
      - 'docker-entrypoint.sh'
      - '.github/workflows/test.yml'
      - '.github/test/**'
      - 'examples/**'
      - 'pom.xml'

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Build & Test ${{ matrix.dockerfile }} - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        dockerfile: [Dockerfile, Dockerfile.alpine, DockerfileSecure]
        os: [ubuntu-latest, macos-15-intel]
    uses: liquibase/build-logic/.github/workflows/reusable-docker-test.yml@main
    with:
      dockerfile_path: ${{ matrix.dockerfile }}
      runs_on: ${{ matrix.os }}
      build_logic_ref: main
    secrets: inherit
